

set(INCLUDE_DRAW2D_CAIRO FALSE)
set(INCLUDE_DIRECT2D TRUE)
set(INCLUDE_DIRECTX11 TRUE)
set(INCLUDE_DIRECTX12 TRUE)
set(INCLUDE_OPENGL TRUE)
set(INCLUDE_VULKAN TRUE)
set(INCLUDE_IMAGING_FREEIMAGE FALSE)
set(INCLUDE_AUDIO FALSE)
set(INCLUDE_OPENGL TRUE)
set(HAS_APP_VERIWELL TRUE)
set(HAS_AUDIO_SYSTEM FALSE)
set(INCLUDE_REDSHIFT FALSE)


